In [138]:

import numpy as np




In [139]:

def diagonal_dominant(x):
    x = np.array(x)
    diags = np.diag(np.abs(x))

    sumx = np.sum(np.abs(x), axis=1)
    non_diags = sumx - diags
    # print(non_diags)
    
    dom = np.all(diags > non_diags)
    return dom

    # is_dominant = True
    # for i in range(3):
    #    xi = np.sum(x[i])
    #    print(xi - diags[i])
    #    if(diags[i] > xi - diags[i]):
    #        continue
    #    is_dominant = False
    #    break
    # return is_dominant



In [140]:


def calc(x, y, t = 15, epsilon = 0.01):
    if(not diagonal_dominant(x)):
       print("not diagonally dominant")
       return

    x = np.array(x)
    y = np.array(y)

    diags_x = np.diag(x)
    print(diags_x)

    x = -x
    np.fill_diagonal(x, 0)
    print(x)

    curr_x = np.zeros(3)
    print("mtx ", curr_x)

    for i in range(t):
        new_x = np.array(curr_x)
        for index, row in enumerate(x):
            print("row ", row)
            new_x[index] = (y[index] + np.dot(row, new_x)) / diags_x[index]

        print("res ", new_x)

        dx = np.sqrt(np.dot(new_x - curr_x, new_x - curr_x))
        if(dx < epsilon):
            print("convergen")
            return
        
        curr_x = new_x

    print("not convergen")




In [141]:


x = [
    [10, 4, 5],
    [1, 6, 1],
    [3, 1, 6]
]

y = [8, 5, 10]

# dd = diagonal_dominant(x)
# print(dd)
calc(x, y)

# r = np.dot(np.array([1, 2, 3]), np.array([2, 2, 4]));
# print("r ", r)



[10  6  6]
[[ 0 -4 -5]
 [-1  0 -1]
 [-3 -1  0]]
mtx  [0. 0. 0.]
row  [ 0 -4 -5]
row  [-1  0 -1]
row  [-3 -1  0]
res  [0.8  0.7  1.15]
row  [ 0 -4 -5]
row  [-1  0 -1]
row  [-3 -1  0]
res  [-0.055       0.65083333  1.58569444]
row  [ 0 -4 -5]
row  [-1  0 -1]
row  [-3 -1  0]
res  [-0.25318056  0.61124769  1.69138233]
row  [ 0 -4 -5]
row  [-1  0 -1]
row  [-3 -1  0]
res  [-0.29019024  0.59980132  1.7117949 ]
row  [ 0 -4 -5]
row  [-1  0 -1]
row  [-3 -1  0]
res  [-0.29581798  0.59733718  1.71501946]
convergen
