In [47]:
import numpy as np
import math

x = [1, 2, 3, 4]
y = [
    [1, 2, 3],
    [3, 4, 5],
    [6, 7, 8]
]



lul = np.array(x)
lul2 = np.array(y)

st = str("kntp")

substr = st[3:]
alph = substr.upper()
alph

pw = np.power(2, 4)

x[:2]

x.insert(2, -1)


for crt in x:
    print("iya ", crt)

for i in range(len(x)):
    print("rangek ", x[i])

for i in range(5):
    print("hem ", i)



iya  1
iya  2
iya  -1
iya  3
iya  4
rangek  1
rangek  2
rangek  -1
rangek  3
rangek  4
hem  0
hem  1
hem  2
hem  3
hem  4


In [51]:
print(lul2.T)



[[1 3 6]
 [2 4 7]
 [3 5 8]]


In [ ]:

x
y

diagdom
diags x
non diags sum xi - diags i

x all abs diags i >  absnon diags

x = -x

fill x diag zero
old = np zeros x shape

new = old
for t times
    for index, row, enum x
        new i = (yi + dot(new, row)) / diag[i]
    dx = sqrt(dot(new - old, new - old))
    if(dx < tol):
        ret
    old = new



In [ ]:

x, y
A = np.vstack([x, np.ones(3)]).T
alpha = np.dot(np.linalg.pinv(A), y)
alp[0] = m
alp[1] = b
y = mx + b
# from matplotlib.pyplot import plot as plt
# plt.plot()


In [ ]:
lr, rr, mid, trapz

f
a, b
n = 3000
w = (b - a) / (n - 1)
x linespace(a, b, n)
lr = w * np.sum(f(x[:-1]))
rr = w * np.sum(f(x[1:]))
mid = x[1:] + x[:-1]/2
mid = w * np sum(f(mid))

trapz = w/2 * f(x[0]) + np sum(f(x[1:-1]) * 2) + f(x[n-1])

In [ ]:
newton raph
target

f
h = 1e-5
f' = f(x + h) - f(x - h) / (2*h)

nr x tol = 0.01
    x0 = x - (f(x) / f'(x))
    if(np.abs(f(x0)) < tol)
        ret
    nr(x0)

In [ ]:
bisec a b tol
    if(np sign a == np sign b)
        ret
    c = (b+a)/2
    if(np abs f(c) < tol)
        ret
    
    if(np sign c == np sign a)
        bisec(c, b)
    elif np sign c == np sign b
        bisec(a, c)