In [47]:
import numpy as np

x = [1, 2, 3, 4]
y = [
    [1, 2, 3],
    [3, 4, 5],
    [6, 7, 8]
]

lul = np.array(x)
lul2 = np.array(y)

st = str("kntp")

substr = st[3:]
alph = substr.upper()
alph

pw = np.power(2, 4)

x[:2]

x.insert(2, -1)


for crt in x:
    print("iya ", crt)

for i in range(len(x)):
    print("rangek ", x[i])

for i in range(5):
    print("hem ", i)



iya  1
iya  2
iya  -1
iya  3
iya  4
rangek  1
rangek  2
rangek  -1
rangek  3
rangek  4
hem  0
hem  1
hem  2
hem  3
hem  4


In [51]:
print(lul2.T)



[[1 3 6]
 [2 4 7]
 [3 5 8]]
