In [1]:
# Gauss-Seidel

# dengan cara mencari hasil gauss jordan dgn, memprediksi x1, x2, dan x3

# sebelum mencari gauss-seidel perlu menentukan diagonal dominant
# yaitu dengan mengecek apakah diagonal (r1c1, r2c2, r3c3) > rc yg tidak diagonal

# setelah mengetahui diagonal dominant, kita memprediksi x1, x2, x3 dgn awalan nilai adalah 0
# dgn mencari x1 menggunakan persamaan 1 dgn cara 10x + 4x2 + 5x3 = 8 menjadi (8 - 4x2 - 5x3)/10 (pindah ruas things)
# lalu mencari x2 dengan persamaan 2 dari x1 + 6x2 + x3 = 5 menjadi (5-x1-x3)/6
# dan mencari x3 dgn persamaan 3

# lalu mulai mencari tiap persamaan tsb dengan iterasi menjadi awalan x2 = 0 dan x3 = 0
# menjadi (8 - 4*0 - 4*0)/10 dimana *0 dari iterasi awal x2 dan x3
# dan menghitung persamaan 2, dan 3 hingga seterusnya sampai iterasi ke N





In [2]:
import numpy as np # perlu library dari numpy ini untuk melakukan perhitungan gauss-seidal

# step
# cek apakah diagonal-dimonant (jika tidak diagonal dominant, maka tidak bisa dihitung)
def is_diagonal_dominant(x):
    # ubah bentuk x menjadi numpy array
    x = np.array(x) # mengubah var x menjadi array numpy, agar bisa menggunakan function2 dari numpy array

    # mendapat nilai diagonal
    # mengambil nilai diagonal dari var x, dimana x adalah array 2d
    # melakukan absolute var x (sesuai rumus diagonal-dominant)
    diagonal = np.diag(np.abs(x))

    # mengambil nilai yg non-diagonal, untuk melakukan perhitungan (dgn value absolute)
    # np.sum() melakukan sum pada satu row pada diagonal x, lalu (- diagonal) untuk mendapat nilai non-diagonal
    # dari dua buah variable (yg tanpa var diagonal)
    # dimana param axis=1 untuk sum secara horizonal
    # dana axis=0 untuk sum secara vertikal 
    non_diagonal = np.sum(np.abs(x), axis=1) - diagonal # pakai axis=1 agar ngesum horizontal
    
    # lalu cek apakah nilai diagonal > non-diagonal (diagonal-dominant things)
    # dimana np.all() untuk cek semua persamaannya (persamaan baris 1, 2, dan 3)
    if(np.all(diagonal > non_diagonal)):
        return True
    # else
    return False


In [3]:

# function utama untuk mencari gauss-seidel
# dgn cara iterasi
# param epsilon untuk memberikan batasan untuk iterasi sampai N berapa (jika perbandingannya sudah < dari epsilon maka stop)
# param t untuk maximum iterasi sampai N berapa
# param x, y untuk nilai x1, x2, x3 dan y untuk nilai pada ruas sebelah
def gauss_seidel(x, y, epsilon=0.01, t=15):
    # cek terlebih dahulu diagonal dominant atau tidak
    if(not is_diagonal_dominant(x)):
        print("Not diagonally dominant") # tidak bisa dilanjutkan
        return
    
    x = np.array(x) # melakukan convertion sama seperti sebelumnya
    y = np.array(y)

    # ambil nilai diagonal (nanti untuk division / diags_x )
    diags_x = np.diag(x)
    # pindah ruas (mengubah x menjadi -x)
    x = -x
    # meng ignore nilai diagonal menjadi 0
    np.fill_diagonal(x, 0) # atau mengubah nilai diagonal menjadi 0
    matrix_old = np.zeros(x[0].shape) # menggunakan row1 menjadi awalan nilai x1, x2, x3 == 0 
    ### tmp: mengambil nilai row 1 dengan x[0].shape (cmiiw maybee)

    for i in range(t): # loop sebanyak maximum, yaitu t
        # menggunakan nilai awal x1, x2, x3 untuk perhitungan
        # iterasi dari matrix old (kalau pertama kali bakal == 0)
        matrix_new = np.array(matrix_old)
        # enumerate untuk iterasi x dan mereturn index dan row nya 
        # (mirip seperti row : List<x> dimana berisi index jg)
        for index, row in enumerate(x): 
            # dimana row untuk hasil iterasi dari dua array enumerate(x)
            # dan index untuk tiap persamaan pada tiap row (cmiiw)
            # np.dot() untuk perkalian dua matrix
            matrix_new[index] = (y[index] + np.dot(row, matrix_new)) / diags_x[index] # melakukan operasi iterasi

        print(f"iterasi {i}: ")
        print(matrix_new)

        # mengecek nilai distance yg old dgn yg new apakah sudah dibawah atau kurang dari var epsilon, maka stop iterasi
        # dgn rumus eucledian distance d = sqrt((x2 - x1)^2 - (x2 - x1)^2)
        dx = np.sqrt(np.dot(matrix_new - matrix_old, matrix_new - matrix_old))
        
        # cek apakah distance sudah kurang dari epsilon
        if(dx < epsilon):
            print("Convergen ") # hasil nilai (Convergen ketika sudah lebih kecil dari batas iterasi)
            return # stop function dan iterate
        
        matrix_old = matrix_new
        
    # update current old ke new untuk perhitungan selanjutnya
    
    # Not Convergen ketika sudah mencapai maximum loop dan belum kurang dari epsilon
    print("Not convergen")



In [4]:

# testing function gauss-sedial
# perlu var persamaan x dan y
x = [
    [10, 4, 5], # persamaan pertama
    [1, 6, 1], # persamaan kedua
    [3, 1, 6] # ketiga
]

y = [8, 5, 10] # untuk y ruas bagian kanan (y persamaan 1, dst)

gauss_seidel(x, y)

iterasi 0: 
[0.8  0.7  1.15]
iterasi 1: 
[-0.055       0.65083333  1.58569444]
iterasi 2: 
[-0.25318056  0.61124769  1.69138233]
iterasi 3: 
[-0.29019024  0.59980132  1.7117949 ]
iterasi 4: 
[-0.29581798  0.59733718  1.71501946]
Convergen 
