In [82]:
import numpy as np

In [83]:
Xs = [
    [10,4,5],
    [1,6,1],
    [3,1,6]
]

Ys = [8,5,10]

In [84]:
def isDiagonallyDominant(x):
    #list ke array
    x = np.array(x)

    #absolute diagonal
    diag = np.array(np.diag(np.abs(x)))

    #axis1 = row
    #axis0 = col
    off_diag = np.sum(np.abs(x), axis=1) - diag 

    if np.all(diag > off_diag):
        return True
    else:
        return False

In [85]:
print(isDiagonallyDominant(Xs))


True


In [86]:
def gauss_seidel(x, y, epsilon=0.015, t=15):
    #1. Konversi X dan Y jadi np.array()
    x = np.array(x)
    y = np.array(y)

    #2. Intialisasi result array using np.zeros()
    result_old = np.zeros(len(x[0]))

    #3. Simpen nilai diagonal, puter balik semuanya dan isi diagonal sebagai 0
    diag = np.diag(x)
    x = -x
    np.fill_diagonal(x ,0)

    #4. Start iterasi
    for i in range(t):
        #gauss-seidel = store newest value
        result_new = np.array(result_old)

        #5. Hitung result
        for j, row in enumerate(x):
            result_new[j] = (y[j] + np.dot(x[j], result_new)) / diag[j]

        print("Iteration:", i + 1)
        print(result_new)
        #6. Count euclidean distance
        euclidean = np.sqrt(np.dot(result_new - result_old,result_new - result_old))

        if euclidean < epsilon:
            return True

        #Kalau belum dapat hasilnya, store old = new
        result_old = result_new

    return False
            
    

In [87]:
gauss_seidel(Xs,Ys)

Iteration: 1
[0.8  0.7  1.15]
Iteration: 2
[-0.055       0.65083333  1.58569444]
Iteration: 3
[-0.25318056  0.61124769  1.69138233]
Iteration: 4
[-0.29019024  0.59980132  1.7117949 ]
Iteration: 5
[-0.29581798  0.59733718  1.71501946]


True

In [88]:
Xs = [
    [
        [6, -2, -3],
        [1, -5, 2],
        [1, 3, 7]
    ],
    [
        [-6, 2, 1],
        [3, -4, 2],
        [2, 1, -3]
    ],
    [
        [12, 10, 1],
        [-2, -10, 3],
        [2, 1, -10]
    ],
    [
        [-3, 1, 2],
        [2, -4, 1],
        [1, 1, -2]
    ],
    [
        [10, -2, -1],
        [1, -13, 2],
        [-1, -1, 8]
    ]
]

Ys = [
    [5, -2, 54],
    [-4, -1, -2],
    [-1, -2, -3],
    [-2, -5, -1],
    [4, -3, 2]
]

In [89]:
for i, (X,Y) in enumerate(zip(Xs,Ys)):
    print(f'Persaman ke-{i+1}')
    # Bisa tambahin diagonally dominant check disini
    if gauss_seidel(X,Y):
        print("CONVERGENT")
    else:
        print("NOT CONVERGENT")
    print('=============\n\n')

Persaman ke-1
Iteration: 1
[0.83333333 0.56666667 7.35238095]
Iteration: 2
[4.6984127  4.28063492 5.20852608]
Iteration: 3
[4.86447468 3.45630537 5.53808703]
Iteration: 4
[4.75447864 3.56613054 5.50673282]
Iteration: 5
[4.77540992 3.55777511 5.50732353]
Iteration: 6
[4.77292014 3.55751344 5.50779136]
CONVERGENT


Persaman ke-2
Iteration: 1
[0.66666667 0.75       1.36111111]
Iteration: 2
[1.14351852 1.78819444 2.02507716]
Iteration: 3
[1.60024434 2.46272184 2.55440351]
Iteration: 4
[1.91330786 2.96218265 2.92959946]
Iteration: 5
[2.14232746 3.32154532 3.20206675]
Iteration: 6
[2.30752623 3.58167805 3.39891017]
Iteration: 7
[2.42704438 3.76973837 3.54127571]
Iteration: 8
[2.51345874 3.90573191 3.64421646]
Iteration: 9
[2.57594671 4.00406827 3.7186539 ]
Iteration: 10
[2.62113174 4.07517575 3.77247974]
Iteration: 11
[2.65380521 4.12659378 3.8114014 ]
Iteration: 12
[2.67743149 4.16377432 3.83954577]
Iteration: 13
[2.69451573 4.19065968 3.85989705]
Iteration: 14
[2.7068694  4.21010058 3.8746